### ISSUE TITLE
Plan for insurance page

### ISSUE THREAD

**Issue by shylands** [GavinShields/storestuff#52]
### Page needs:
- [x] Title
- [x] global description of what insurance is
- [x] a list of insurance products

### List items should contain:
- [x] Price
- [ ] Name
- [x] Description?
- [ ] Image? If so what would it be?
- [ ] Button to buy

Pressing buy should take them to a hosted page to checkout.

Upon purchase they should be redirected to a insurance purchase confirmation screen

**Comment by shylands** [comment]
@GavinShields please take a look at the above and confirm what you want.

Questions:
1) Do you want individual pages for each insurance item as well as a list view?
2) What should the main url be? /insurance?

**Comment by GavinShields** [comment]
1. I don't think I'll need that, no
2. /insurance seems to make the most sense

Title: Store Stuff insurance
Global description of what product is: Insurance for your goods while stored with StoreStuff. 
List of insurance products:
1. £1k cover, £2.99/month, £1k of insurance cover, no image, 
2. £2.5k cover, £4.99/month, £2.5k of insurance cover, no image
3. £5k cover, £8.99/month, £5k of insurance cover, no image
4. £10k cover, £14.99/month, £10k of insurance cover, no image
5. £20k cover, £22.99/month, £20k of insurance cover, no image

**Comment by GavinShields** [comment]
some additional sectoins relevant to this page:

INtroduction text:

We know your possessions are valuable and our facilities are designed with security and safety in mind. Each unit is individually alarmed and fitted with internal heat and motion sensors. The facility also has 24 hour CCTV. 

However, the unexpected can happen and for everyone's peace of mind, we need to know that all customers goods are covered at all times. There are two ways to you can do this. 

Option 1: Take out your own insurance. Most home insurance policies do not cover items in self storage, but it is worth checking your policy. We will need to see proof of your cover within 7 days of moving in to the facility and you can email it to insurance@storestuffni.com.

Option 2: Take advantage of our low cost, hassle-free insurance options starting from just £2.99 per month. 


Terms:

What is included:
- All loss, destruction or damage to the Customer's Property, with a new for old basis of cover (except documents).
- Physical loss or damage to your property caused by burst pipes or escape of water
- Theft accompanied by forcible and violent entry or exit
- Moth, insect or vermin damage from an external source
- Fire
- Lightning
- Explosion
- Earthquake
- Storm
- Flood
- Riot
- Strike
- Civil commotion
- Malicious damage
- Impact by vehicles and aircraft

What is not covered:
- First £50 for each and every loss;
- Maximum of £25,000 of goods per customer;
- Money, coins, bullion, deeds, bonds, securities, digitally or otherwise stored cryptocurrencies or similar virtual or decentralised currencies;
- Livestock, plants or perishable goods of any kind;
- Jewellery, watches, precious stones, precious metals, and stamps of all kinds exceeding
£1,000 in total;
- Furs, fine arts, mobile phones, perfumery, tobacco, cigars, cigarettes, beers, wines, spirits
and the like; exceeding £15,000 combined total;
- Electronic items exceeding £15,000 in total.
- Explosives and flammables

Main exclusions: 
- Loss or theft of any item other than following violent and forcible entry to or exit from the
storage unit.
- Accidental damage to any property caused by the Customer.
- Loss or damage occurring during loading or unloading and transit, unless transportation into
or out of store is arranged by the Self Storage Operator.
- Loss or damage caused by moth, insect and vermin unless from a source external to the
Customer’s own storage unit.
- Any financial loss other than loss, destruction or damage to the property insured.
- Pairs and sets.
- Electrical, electronic or mechanical derangement.
